language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t emiyauwb6/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=True emiyaubw6/docker-react npm run test

